# Generated by Django 4.0.6 on 2022-09-04 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_manager", "0004_alter_image_uploader"),
        ("item", "0003_useritem_unique_item_by_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[("map", "map"), ("animal", "animal"), ("item", "item")],
                default="map",
                max_length=30,
                verbose_name="아이템 종류",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(max_length=30, verbose_name="아이템명"),
        ),
        migrations.AlterField(
            model_name="item",
            name="point",
            field=models.PositiveIntegerField(default=0, verbose_name="아이템 가격"),
        ),
        migrations.AlterField(
            model_name="item",
            name="thumbnail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="file_manager.image",
                verbose_name="아이템 이미지",
            ),
        ),
    ]
