# Generated by Django 4.0.6 on 2022-09-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0006_itemcondition_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[("map", "map"), ("animal", "animal"), ("item", "item"), ("tree", "tree")],
                default="map",
                max_length=30,
                verbose_name="아이템 종류",
            ),
        ),
    ]
