# Generated by Django 4.0.6 on 2022-09-12 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0007_alter_item_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="display_order",
            field=models.IntegerField(default=0, verbose_name="표시 순서"),
        ),
    ]
