# Generated by Django 4.0.6 on 2022-09-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0005_alter_useritem_item_alter_useritem_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemcondition",
            name="priority",
            field=models.IntegerField(default=0, verbose_name="우선순위(낮을 수록 먼저 적용되어야 함.)"),
        ),
    ]
