version: '3'
services:
  webapp:
    env_file:
      - ./.env
    volumes:
      - ./webapp:/usr/src/app
      - ./logs:/var/logs/
      - staticfiles:/usr/src/app/static
      - mediafiles:/usr/src/app/media
    build:
      context: ./webapp
      dockerfile: ./Dockerfile.production
    image: webapp-image
    container_name: webapp-container
    entrypoint:
      - /docker-entrypoint.sh
    depends_on:
      - db
  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile.production
    image: nginx-image
    container_name: nginx-container
    ports:
      - 80:80
    depends_on:
      - webapp
    links:
      - webapp
    entrypoint:
      - /docker-entrypoint.sh
    volumes:
      - staticfiles:/static
      - mediafiles:/media
      - ./logs:/var/log/nginx
  db:
    image: postgres
    expose:
      - "${POSTGRES_PORT}"
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - ./db/initial_setup.sql:/docker-entrypoint-initdb.d/initial_setup.sql
      - postgres_data:/var/lib/postgresql/data/
    command: -p ${POSTGRES_PORT}

volumes:
  postgres_data:
  staticfiles:
  mediafiles:
