# Generated by Django 4.0.6 on 2022-08-29 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0004_alter_article_writer_alter_challengearticle_article_and_more"),
        ("file_manager", "0002_challengeimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="추가된 일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정된 일시")),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="article_images", to="article.article"
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article_images",
                        to="file_manager.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "ArticleImage",
                "verbose_name_plural": "ArticleImages",
                "db_table": "article_images",
            },
        ),
    ]
