# Generated by Django 4.0.6 on 2022-08-25 10:34

import user.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_created_at_user_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=user.models.user.user_avatar_upload_path, verbose_name="프로필 이미지"
            ),
        ),
    ]
