# Generated by Django 4.0.6 on 2022-09-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("point", "0005_point_article_point_challenge_point_item_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="point",
            name="point_category",
        ),
        migrations.AddField(
            model_name="point",
            name="category",
            field=models.CharField(
                choices=[("buy_item", "아이템 구매"), ("prove_challenge", "챌린지 인증 글 작성")],
                max_length=30,
                null=True,
                verbose_name="포인트 종류",
            ),
        ),
    ]
