# Generated by Django 4.0.6 on 2022-09-03 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0010_alter_article_images"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articleuserfeedback",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="article_user_feedbacks", to="article.article"
            ),
        ),
        migrations.AlterField(
            model_name="articleuserfeedback",
            name="feedback",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="article_user_feedbacks",
                to="feedback.feedback",
            ),
        ),
        migrations.AlterField(
            model_name="articleuserfeedback",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="article_user_feedbacks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
