# Generated by Django 4.0.6 on 2022-08-26 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("challenge", "0007_alter_challengecategory_category_and_more"),
        ("article", "0003_challengearticle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="writer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="작성자",
            ),
        ),
        migrations.AlterField(
            model_name="challengearticle",
            name="article",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="challenge_articles",
                to="article.article",
            ),
        ),
        migrations.AlterField(
            model_name="challengearticle",
            name="challenge",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="challenge_articles",
                to="challenge.challenge",
            ),
        ),
        migrations.AlterModelTable(
            name="article",
            table="articles",
        ),
        migrations.AlterModelTable(
            name="challengearticle",
            table="challenge_articles",
        ),
    ]
