# Generated by Django 4.0.6 on 2022-08-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_manager", "0003_articleimage"),
        ("article", "0004_alter_article_writer_alter_challengearticle_article_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="images",
            field=models.ManyToManyField(
                related_name="images", through="file_manager.ArticleImage", to="file_manager.image"
            ),
        ),
    ]
