# Generated by Django 4.0.6 on 2022-08-31 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenge", "0011_challengesuggestionfeedback_unique_suggestion_by_user"),
        ("article", "0007_delete_challengearticle"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="challenge",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="challenge.challenge",
            ),
        ),
    ]
