# Generated by Django 4.0.6 on 2022-09-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0004_notification_article_notification_challenge_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="추가된 일시"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notice_category",
            field=models.IntegerField(
                choices=[("challenge", "챌린지 인증글 댓글 알림"), ("piece", "피스글 댓글 알림"), ("category", "카테고리 챌린지 알림")],
                default=0,
                verbose_name="알림 종류",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="수정된 일시"),
        ),
    ]
