# Generated by Django 4.0.6 on 2022-09-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0005_alter_notification_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notice_category",
            field=models.CharField(
                choices=[("challenge", "챌린지 인증글 댓글 알림"), ("piece", "피스글 댓글 알림"), ("category", "카테고리 챌린지 알림")],
                max_length=30,
                verbose_name="알림 종류",
            ),
        ),
    ]
