# Generated by Django 4.0.6 on 2022-09-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0006_alter_notification_notice_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="is_viewed",
            field=models.BooleanField(default=False),
        ),
    ]
