# Generated by Django 4.0.6 on 2022-08-21 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("challenge", "0002_challengesuggestion"),
        ("challenge", "0003_challengereminder"),
    ]

    operations = []
