# Generated by Django 4.0.6 on 2022-08-23 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("challenge", "0003_challengesuggestionfeedback"),
        ("challenge", "0005_category_created_at_category_updated_at_and_more"),
    ]

    operations = []
