# Generated by Django 4.0.6 on 2022-08-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenge", "0011_challengesuggestionfeedback_unique_suggestion_by_user"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="challengereminder",
            constraint=models.UniqueConstraint(fields=("user", "category"), name="unique_category_by_user"),
        ),
    ]
