# Generated by Django 4.0.6 on 2022-09-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenge", "0013_rename_feedback_cnt_challengesuggestion_feedback_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="end_at",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="start_at",
            field=models.DateField(),
        ),
    ]
