FROM nginx:1.21.4

# Configure Nginx
COPY nginx.production.conf /etc/nginx/nginx.conf

# Copy Script to Wait for Gunicorn
COPY wait-for-it.sh /wait-for-it.sh

# Copy Entrypoint Script
COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh
