# Generated by Django 4.0.6 on 2022-08-26 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenge", "0007_alter_challengecategory_category_and_more"),
        ("file_manager", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChallengeImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="추가된 일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정된 일시")),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenge_images",
                        to="challenge.challenge",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenge_images",
                        to="file_manager.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "ChallengeImage",
                "verbose_name_plural": "ChallengeImages",
                "db_table": "challenge_images",
            },
        ),
    ]
