# Generated by Django 4.0.6 on 2022-09-03 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("file_manager", "0003_articleimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="uploader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploader",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
