# Generated by Django 4.0.6 on 2022-08-21 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenge', '0002_category_challengecategory_challenge_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ChallengeReminder',
                'verbose_name_plural': 'ChallengeReminders',
                'db_table': 'challenge_reminder',
            },
        ),
    ]
