# Generated by Django 4.0.6 on 2022-08-26 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("challenge", "0006_merge_20220823_2225"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challengecategory",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="challenge_categories",
                to="challenge.category",
            ),
        ),
        migrations.AlterField(
            model_name="challengecategory",
            name="challenge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="challenge_categories",
                to="challenge.challenge",
            ),
        ),
        migrations.AlterField(
            model_name="challengesuggestion",
            name="challenge",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="challenge_suggestion",
                to="challenge.challenge",
                verbose_name="챌린지",
            ),
        ),
        migrations.AlterField(
            model_name="challengesuggestion",
            name="suggester",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="challenge_suggestions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="제안자",
            ),
        ),
        migrations.AlterField(
            model_name="challengesuggestionfeedback",
            name="suggestion",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="challenge_suggestion_feedbacks",
                to="challenge.challengesuggestion",
                verbose_name="챌린지 제안",
            ),
        ),
        migrations.AlterField(
            model_name="challengesuggestionfeedback",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="challenge_suggestion_feedbacks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="피드백 유저",
            ),
        ),
        migrations.AlterModelTable(
            name="category",
            table="categories",
        ),
        migrations.AlterModelTable(
            name="challenge",
            table="challenges",
        ),
        migrations.AlterModelTable(
            name="challengecategory",
            table="challenge_categories",
        ),
        migrations.AlterModelTable(
            name="challengereminder",
            table="challenge_reminders",
        ),
        migrations.AlterModelTable(
            name="challengesuggestion",
            table="challenge_suggestions",
        ),
        migrations.AlterModelTable(
            name="challengesuggestionfeedback",
            table="challenge_suggestion_feedbacks",
        ),
    ]
