# Generated by Django 4.0.6 on 2022-08-28 11:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenge", "0009_challenge_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="challengesuggestionfeedback",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="추가된 일시"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="challengesuggestionfeedback",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="수정된 일시"),
        ),
    ]
