# Generated by Django 4.0.6 on 2022-08-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenge", "0010_challengesuggestionfeedback_created_at_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="challengesuggestionfeedback",
            constraint=models.UniqueConstraint(fields=("user", "suggestion"), name="unique_suggestion_by_user"),
        ),
    ]
