# Generated by Django 4.0.6 on 2022-09-02 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("challenge", "0012_challengereminder_unique_category_by_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="challengesuggestion",
            old_name="feedback_cnt",
            new_name="feedback_count",
        ),
    ]
