# Generated by Django 4.0.6 on 2022-09-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenge", "0014_alter_challenge_end_at_alter_challenge_start_at"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="challengecategory",
            constraint=models.UniqueConstraint(fields=("category", "challenge"), name="unique_category_by_challenge"),
        ),
    ]
