# Generated by Django 4.0.6 on 2022-09-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0005_alter_useritem_item_alter_useritem_user"),
        ("user", "0003_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="items",
            field=models.ManyToManyField(related_name="users", through="item.UserItem", to="item.item"),
        ),
    ]
