# Generated by Django 4.0.6 on 2022-09-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_user_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="point",
            field=models.IntegerField(default=0, verbose_name="소지 포인트"),
        ),
    ]
