# Generated by Django 4.0.6 on 2022-08-30 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0005_article_images"),
        ("article", "0005_comment_articlecomment"),
    ]

    operations = []
