# Generated by Django 4.0.6 on 2022-08-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0008_article_challenge"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="article",
            constraint=models.UniqueConstraint(fields=("writer", "challenge"), name="unique_challenge_article_by_user"),
        ),
    ]
