# Generated by Django 4.0.6 on 2022-08-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_manager", "0003_articleimage"),
        ("article", "0009_article_unique_challenge_article_by_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="images",
            field=models.ManyToManyField(
                related_name="articles", through="file_manager.ArticleImage", to="file_manager.image"
            ),
        ),
    ]
