# Generated by Django 4.0.6 on 2022-09-02 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("article", "0010_alter_article_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articlecomment",
            name="comment",
        ),
        migrations.AddField(
            model_name="articlecomment",
            name="content",
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name="내용"),
        ),
        migrations.AddField(
            model_name="articlecomment",
            name="writer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="작성자",
            ),
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
